{
 "title": "GPU View",
 "tags": [ "Moneo" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(dcgm_gpu_utilization,subscription)"
    }
   },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(dcgm_gpu_utilization{subscription=\"$Subscription\"}, cluster)"
    }
   },
   {
    "name": "JobId",
    "label": "Job Id",
    "query": {
     "query": "label_values(dcgm_gpu_utilization{cluster=~\"$Cluster\"}, job_id)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(dcgm_gpu_utilization{cluster=\"$Cluster\", job_id=~\"$JobId\"}, instance)"
    }
   },
   {
    "name": "GPU",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_gpu_utilization{instance=~\"$Instance\"},gpu_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  { "title": "Clock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SM Clock",
   "type": "timeseries",
   "description": "Selected Operation on VM GPU device SM Clock",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_sm_clock{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Memory Clock",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_memory_clock{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  { "title": "NV Link", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "NVLink TX Rate",
   "type": "timeseries",
   "description": "The rate of data transmitted over NVLink.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcgm_nvlink_tx_bytes{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{ib_port}}"
    }
   ]
  },
  {
   "title": "NVLink RX Rate",
   "type": "timeseries",
   "description": "The rate of data received over NVLink.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "dcgm_nvlink_rx_bytes{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{ib_port}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU device Temperature",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_gpu_temp{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  {
   "title": "Mem Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_memory_temp{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Selected Operation of VM GPU Power",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dcgm_power_usage{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "dcgm_total_energy_consumption{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
     "legendFormat": "{{instance}}:{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Throttle Code",
     "type": "timeseries",
     "description": "Current throttle code ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "dcgm_current_clock_throttle_reasons{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ECC Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "SBE Volatile ECC Errors",
     "type": "timeseries",
     "description": "Total number of single-bit volatile ECC errors",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "dcgm_ecc_sbe_volatile_total{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    },
    {
     "title": "DBE Volatile ECC Errors",
     "type": "timeseries",
     "description": "Total number of double-bit volatile ECC errors",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "expr": "dcgm_ecc_dbe_volatile_total{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    },
    {
     "title": "DBE Persistent ECC Errors",
     "type": "timeseries",
     "description": "Total number of double-bit persistent ECC errors",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "dcgm_ecc_dbe_aggregate_total{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    },
    {
     "title": "SBE Persistent ECC Errors",
     "type": "timeseries",
     "description": "Total number of single-bit persistent ECC errors",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
     "targets": [
      {
       "expr": "dcgm_ecc_sbe_aggregate_total{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Instance to Host Mapping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM to Physical Host Map",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
     "targets": [
      {
       "expr": "dcgm_gpu_temp{subscription=\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\",gpu_id=\"0\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Burn Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "node_gpu_burn_mon{subscription=~\"$Subscription\", cluster=~\"$Cluster\", instance=~\"$Instance\", gpu_id=~\"$GPU\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    },
    {
     "title": "meta_seq wps per GPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "node_meta_seq_mon{subscription=~\"$Subscription\", cluster=\"$Cluster\", instance=~\"$Instance\"}",
       "legendFormat": "{{instance}}:{{gpu_id}}"
      }
     ]
    }
   ]
  }
 ]
}