{
 "title": "Network Counters",
 "description": "Network Counters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job_id", "label": "Job id", "query": { "query": "label_values(job_id)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({ job_id=~\"$job_id\"}, instance)"
    }
   },
   { "name": "ib_port", "label": "InfiniBand", "query": { "query": "label_values(ib_port)" } }
  ]
 },
 "panels": [
  { "title": "InfiniBand", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IB TX Rate",
   "type": "graph",
   "description": "The rate of data transmitted over InfiniBand.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ib_port_xmit_data{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  {
   "title": "IB RX Rate",
   "type": "graph",
   "description": "The rate of data received over InfiniBand.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ib_port_rcv_data{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  { "title": "Port Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Port Xmit Discards",
   "type": "timeseries",
   "description": "Total number of outbound packets discarded by the port because the port is down or congested.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ib_port_xmit_discards{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  {
   "title": "Port Xmit Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets not transmitted from the switch physical port.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ib_port_xmit_constraint_errors{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  {
   "title": "Port Rcv Errors",
   "type": "timeseries",
   "description": "Total number of packets containing an error that were received on the port.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ib_port_rcv_errors{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  {
   "title": "Port Rcv Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets received on the switch physical port that are discarded.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ib_port_rcv_constraint_errors{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  {
   "title": "IB Link Status",
   "type": "timeseries",
   "description": "Indication of IB Link status. Up:1 and Down:0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ib_port_physical_state{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  },
  {
   "title": "Last Link Flap",
   "type": "table",
   "description": "Indication of IB Link Flap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_link_flap{job_id=~\"$job_id\",instance=~\"$instance\", ib_port=~\"$ib_port\"}",
     "legendFormat": "{{ib_port}}"
    }
   ]
  }
 ]
}